name: Move assigned card
on:
  pull_request:
    branches:
      - main
      
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: silvio-teste
          column: Pronto
          repo-token: ${{ secrets.MY_TOKEN }}
