name: Mover Issue
on:
  push:
    branches:
      - test_runer 
jobs:
  cycle-weekly-close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: weekly-issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: marretada
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
