name: Mover Issue

on:
  push:
    branches:
      - main

jobs:
  move_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar o ambiente Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependências
        run: |
            cd .github/workflows/move-issues-project
            npm install

      - name: Mover Issue
        run: node .github/workflows/move-issues-project/move-issue.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}